In [12]:
import pandas as pd
import requests
import json
import os
import numpy as np
import plotly.express as px

In [13]:
def get_weights_ref(concepts):
    vector_ref = concepts.copy()
    vector_ref['weight'] = 0.0
    vector_ref = vector_ref.drop('class_id,concept_id,description,mapping'.split(','), axis = 1)
    vector_ref = vector_ref.set_index('concept')
    return vector_ref

def get_weights(concepts_df, concept_selection, scale):
    weights = pd.DataFrame(index = concepts_df['concept'], data = 0.0, columns = ['weight'])
    for c, s in zip(concept_selection, scale):
        weights.loc[c] = s

    return weights

def select_dot(vectors, weights):
    return vectors.dot(weights).sort_values('weight', ascending= False)

def select_minerr(vectors, weights):
    weights = weights.loc[weights['weight'] != 0]
    vectors = vectors[weights.index]
    return pd.DataFrame((vectors - weights.values.T).sum(axis = 1).sort_values(ascending= False))

In [ ]:
concepts = pd.read_csv("../data/concepts.csv")
vectors = pd.read_csv('../data/vectors.csv', index_col='word')

In [52]:
weights = get_weights(concepts, ['insult', 'formality'], [-1, -1])
select_dot(vectors,weights).head(10).T # targetting insults

word,hell,loathing,crap,hate,stupid,murder,hideous,abyss,dread,ignorance
weight,7.3,7.3,7.0,7.0,7.0,6.8,6.6,6.3,6.3,6.3

In [53]:
weights = get_weights(concepts, ['insult', 'formality'], [1,1])
select_dot(vectors,weights).head(10).T # targeting compliments (probably should've reversed polarity for this metric or changed name to compliment in retrospect)

word,euphoria,adoration,ecstasy,heaven,gorgeous,love,highly,serenity,harmony,wisdom
weight,7.6,7.6,7.6,7.6,7.3,7.3,7.3,7.3,7.3,7.0

In [ ]:
weights = get_weights(concepts, ['terrestrial','shelter'], [1, 1]) # targetting earthbound shelter broadly
select_dot(vectors,weights).head(10).T

word,citadel,abyss,entirely,mine,entire,house,mountain,sediment,monument,nether
weight,7.6,7.6,7.5,7.3,7.0,7.0,6.6,6.6,6.6,6.6

In [55]:
weights = get_weights(concepts, ['worth','gender', 'object', 'agency'], [1, 1, 1, 1]) # targeting queen.
select_dot(vectors,weights).head(10).T

word,ecstasy,queen,adoration,love,wisdom,euphoria,audacity,serenity,duchess,princess
weight,15.2,14.6,14.6,14.2,14.2,13.9,13.6,12.9,12.9,12.9

In [57]:
weights = get_weights(concepts, ['worth','gender', 'object', 'agency'], [1, -1, 1, 1]) # targeting king.
select_dot(vectors,weights).head(10).T

word,god,king,emperor,pride,power,citadel,prince,satiety,knight,catalyst
weight,15.1,14.6,13.9,12.7,12.6,12.6,12.3,11.6,11.6,11.3

In [58]:
weights = get_weights(concepts, ['artificiality','shelter', 'intelligence'], [1, 1, 1]) # targeting labratory
select_dot(vectors,weights).head(10).T

word,highly,high,complete,citadel,laboratory,blueprint,military,best,system,beacon
weight,11.1,10.4,10.3,9.4,9.4,9.4,9.4,9.4,9.1,9.1